# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 635)
        MainWindow.setMinimumSize(QtCore.QSize(635, 635))
        MainWindow.setMaximumSize(QtCore.QSize(635, 635))
        MainWindow.setStyleSheet("background-image: url(:/BG/bg.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(210, 20, 200, 51))
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 51))
        self.textBrowser.setMaximumSize(QtCore.QSize(491, 51))
        self.textBrowser.setStyleSheet("background-image: url(:/BG/W.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 90, 551, 371))
        self.plainTextEdit.setStyleSheet("background-image: url(:/BG/W.png);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(410, 520, 181, 41))
        self.lineEdit.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/BG/W.png);")
        self.lineEdit.setObjectName("lineEdit")
        self.bookstorebutton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bookstorebutton_4.setGeometry(QtCore.QRect(40, 520, 179, 40))
        self.bookstorebutton_4.setStyleSheet("background-image: url(:/BG/W.png);\n"
"font: 16pt \"Nirmala UI\";")
        self.bookstorebutton_4.setObjectName("bookstorebutton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 520, 111, 41))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/BG/W.png);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 470, 551, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bookstorebutton_2 = QtWidgets.QPushButton(self.widget)
        self.bookstorebutton_2.setStyleSheet("background-image: url(:/BG/W.png);\n"
"font: 16pt \"Nirmala UI\";")
        self.bookstorebutton_2.setObjectName("bookstorebutton_2")
        self.horizontalLayout.addWidget(self.bookstorebutton_2)
        self.bookstorebutton_3 = QtWidgets.QPushButton(self.widget)
        self.bookstorebutton_3.setStyleSheet("background-image: url(:/BG/W.png);\n"
"font: 16pt \"Nirmala UI\";")
        self.bookstorebutton_3.setObjectName("bookstorebutton_3")
        self.horizontalLayout.addWidget(self.bookstorebutton_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.85455pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">ORDER</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", " "))
        self.bookstorebutton_4.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "  Total Price"))
        self.bookstorebutton_2.setText(_translate("MainWindow", "Buy"))
        self.bookstorebutton_3.setText(_translate("MainWindow", "clear order"))
import Image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
